root: true

env:
  browser: false
  worker: true
  node: true
  es6: true

extends:
  - 'scalecore'

parserOptions:
  ecmaVersion: 2018
  sourceType: module

reportUnusedDisableDirectives: true

overrides:
  - files: ['*.ts', '*.tsx']
    parserOptions:
      project: tsconfig.json
    rules:
      # Naming convention
      '@typescript-eslint/naming-convention':
        - error
        # By default, most everything should be camel case.
        - selector: default
          format: [camelCase]
          leadingUnderscore: allow
        # Types should only be Pascal cased.
        - selector: [typeLike]
          format: [PascalCase]
        # If a property in a literal requires quoting, it will likely break our naming conventions.
        - selector: [objectLiteralProperty, objectLiteralMethod]
          modifiers: [requiresQuotes]
          format: null
